# Jekyll Settings
permalink: "/meetings/:year/:month/:day/:title"
markdown: kramdown
highlighter: rouge
future: true
show_drafts: false
time_zone: "US/Central"
excerpt_separator: <!--more-->
empty_array: []

kramdown:
    input: GFM          # use Github Flavored Markdown    
    hard_wrap: false    # do not replace newlines by <br>s
    
sass:
    sass_dir: _sass

plugins_dir: ['jekyll-sitemap']
exclude: ['README.md',
    'Gemfile',
    'Gemfile.lock',
    'screenshot.png',
    'servesite.bat',
    'LICENSE',
    'OldSiteConversionScript',
    'vagrant']
    
# Collections
collections:
    sponsors:
        output: true
        permalink: /sponsors/:name/
    persons:
        output: true
        permalink: /people/:name/
    locations:
        output: false
    meetingyears:
        output: true
        permalink: /meetings/:name/
    events:
        output: true
        permalink: /events/:name/

  
# defaults
defaults:
  - scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
      is_meeting: true # most posts are meetings. set this to false in post if non-meeting      
      layout: post     
  - scope:
      path: ""
      type: sponsors
    values:
      layout: sponsor
      title_pretext: "About "
  - scope:
      path: ""
      type: persons
    values:
      layout: "person"
      title_pretext: "About "
  - scope:
      path: ""
      type: meetingyears
    values:
      layout: meetingyear
      title_posttext: " Meetings"
  - scope:
      path: ""
      type: events
    values:
      layout: event
      title_posttext: ""

     
# Site Properties
title: North Houston .Net Users Group
description: 'A programmers meetup'
url: 'https://www.nhdnug.org'
baseurl: ''
# google_analytics: ''
