# Jekyll Settings
paginate: 10
paginate_path: "/events/page:num"
permalink: "/events/details/:year/:month/:day/:title"
markdown: kramdown
highlighter: rouge
future: true
show_drafts: false
time_zone: "US/Central"
excerpt_separator: <!--more-->

kramdown:
    input: GFM          # use Github Flavored Markdown    
    hard_wrap: false    # do not replace newlines by <br>s

gems: ['jekyll-paginate', 'jekyll-sitemap']
exclude: ['README.md',
    'Gemfile',
    'Gemfile.lock',
    'screenshot.png',
    'servesite.bat',
    'LICENSE',
    'OldSiteConversionScript']
    
# Collections
collections:
    sponsors:
        output: true
        permalink: /sponsors/:name/
    speakers:
        output: true
        permalink: /speakers/:name/
    locations:
        output: false

# Site Properties
title: North Houston .Net Users Group
description: 'A programmers meetup'
url: 'http://nhdnug.github.io'
baseurl: ''
# google_analytics: ''
disqus_shortname: 'nhdnug'

author:
  name: 'North Houston .Net Users Group'
  email: info@nhdnug.org
  twitter_username: nhdnug
  facebook_username: nhdnug
  github_username:  nhdnug
  linkedin_username:

# defaults
defaults:
  - scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
      layout: post     
  - scope:
      path: ""
      type: sponsors
    values:
      layout: sponsor
      title_pretext: "About "
  - scope:
      path: ""
      type: speakers
    values:
      layout: "speaker"
      title_pretext: "About "
     