# Jekyll Settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
future: true
show_drafts: false

kramdown:
    input: GFM          # use Github Flavored Markdown    
    hard_wrap: false    # do not replace newlines by <br>s

gems: ['jekyll-paginate', 'jekyll-sitemap']
exclude: ['README.md',
    'Gemfile',
    'Gemfile.lock',
    'screenshot.png',
    'servesite.bat',
    'LICENSE',
    'OldSiteConversionScript']

# Site Properties
title: North Houston .Net User Group
description: 'A programmers meetup'
url: 'http://nhdnug.github.io'
baseurl: ''
# google_analytics: ''
disqus_shortname: 'nhdnug'

author:
  name: 'North Houston .Net User Group'
  email: info@nhdnug.org
  twitter_username: nhdnug
  facebook_username: nhdnug
  github_username:  nhdnug
  linkedin_username:

# defaults
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts